name: flutter_news
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  workmanager: ^0.5.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  url_launcher: ^6.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true